In [2]:
pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 290.5 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 249.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB 991.0 kB/s eta 0:00:17
   ---------------------------------------- 0.2/16.5 MB 2.0 MB/s eta 0:00:09
    --------------------------------------- 0.3/16.5 MB 2.9 MB/s eta 0:00:06
   - -------------------------------------- 0.7/16.5 MB 4.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/16.5 MB 8.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.9/16.5 MB 11.6 MB/s eta 0:00:02



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: C:\Users\anwes\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [9]:

def adjm(edges,nodes):
    import numpy as np
    a = np.zeros(shape=(nodes, nodes)) #empty matrix where every value is zero, i.e. not reachable
    
    # making one where they're reachable
    for (i,j) in edges:
        a[i][j] = 1

    return (a)



In [7]:
edges = [[0,1], [0,4], [1,2], [2,0], [3,4],
         [3,6], [4,0], [4,3], [4,7], [5,3],
         [5,7], [6,5], [7,4], [7,8], [8,5],
         [8,9], [9,8]]

In [10]:
print(adjm(edges, 10))

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
