In [1]:
edges = [[0,1], [0,4], [1,2], [2,0], [3,4],
         [3,6], [4,0], [4,3], [4,7], [5,3],
         [5,7], [6,5], [7,4], [7,8], [8,5],
         [8,9], [9,8]]

In [2]:

def adjm(edges,nodes):
    import numpy as np
    a = np.zeros(shape=(nodes, nodes)) #empty matrix where every value is zero, i.e. not reachable
    
    # making one where they're reachable
    for (i,j) in edges:
        a[i][j] = 1

    return (a)


In [12]:
def adjl(edges, nodes):
    alist = {}
    for i in range(nodes):
        alist[i] = []
    for (i,j) in edges:
        alist[i].append(j)

    return(alist)
    

In [3]:
class Queue:
    def __init__(self) :
        self.queue = []

    def isempty(self):
        return (self.queue == [])
    
    def addq(self, v):
        self.queue.append(v)

    def delq(self):
        v = None
        if not self.isempty:
            v = self.queue[0]
            self.queue = self.queue[1:]
        return (v)
    
    def __str__(self) -> str:
        return (str(self.queue))

In [4]:
def neighbours(adjm, v):
    import numpy as np
    neighbours = []
    (rows,cols) = np.shape(adjm)
    for i in range(cols):
        if adjm[v][i] == 1:
            neighbours.append(i)
    return (neighbours)


In [13]:
amat = adjm(edges,10)
alist = adjl(edges,10)

print("The adjacency matrix is ")
print(amat)
print("The adjacency list is ")
print(alist)


The adjacency matrix is 
[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
The adjacency list is 
{0: [1, 4], 1: [2], 2: [0], 3: [4, 6], 4: [0, 3, 7], 5: [3, 7], 6: [5], 7: [4, 8], 8: [5, 9], 9: [8]}


In [16]:
def BFS_list(Alist, v):
    visited, parent = {}, {}
    for i in list(Alist.keys()):
        visited[i] = False
        parent[i] = -1

    visited[v] = True
    q = Queue()
    q.addq(v)

    while (not q.isempty()):
        j = q.delq()
        for k in Alist[j]:
            if (not visited[k]):
                visited[k] = True
                parent[k] = j
                q.addq(k)

    return(visited,parent)

In [8]:
def BFS_matrix(matrix, v):
    import numpy as np
    rows, cols = np.shape(matrix)
    visited, parent = {}, {}
    for i in range(rows):
        visited[i] = False
        parent[i] = -1

    visited[v] = True
    q = Queue()
    q.addq(v)

    while (not q.isempty()):
        j = q.delq()
        for k in neighbours(matrix, j):
            if visited[k] == False:
                visited[k] = True
                parent[k] = j
                q.addq(k)

    return(visited, parent)

In [17]:
(visited, parents) = BFS_list(alist,1)

KeyError: None