In [1]:
class Queue:
    def __init__(self):
        self.queue = []

    def addq(self,v):
        self.queue.append(v)

    def delq(self):
        v = None
        if not self.isempty():
            v = self.queue[0]
            self.queue = self.queue[1:]
        return(v)

    def isempty(self):
        return(self.queue == [])

    def __str__(self):
        return(str(self.queue))

In [2]:
# Dijkstra example
dedges = [(0,1,10),(0,2,80),(1,2,6),(1,4,20),(2,3,70),(4,5,50),(4,6,5),(5,6,10)]
edges = dedges + [(j,i,w) for (i,j,w) in dedges]

In [ ]:
size = 7
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1 # becase these edges exist
    W[i,j,1] = w
print(W)

[[[ 0.  0.]
  [ 1. 10.]
  [ 1. 80.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 1. 10.]
  [ 0.  0.]
  [ 1.  6.]
  [ 0.  0.]
  [ 1. 20.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 1. 80.]
  [ 1.  6.]
  [ 0.  0.]
  [ 1. 70.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 1. 70.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 1. 20.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 50.]
  [ 1.  5.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 50.]
  [ 0.  0.]
  [ 1. 10.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  5.]
  [ 1. 10.]
  [ 0.  0.]]]


In [ ]:
np.max(W)

80.0

In [ ]:
def dijkstra(WMat,s):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows+1
    (visited,distance) = ({},{})
    for v in range(rows):
        (visited[v],distance[v]) = (False,infinity)

    distance[s] = 0

    for u in range(rows):
        nextd = min([distance[v] for v in range(rows)
                        if not visited[v]])
        nextvlist = [v for v in range(rows)
                        if (not visited[v]) and
                            distance[v] == nextd]
        if nextvlist == []:
            break
        nextv = min(nextvlist)

        visited[nextv] = True
        for v in range(cols):
            if WMat[nextv,v,0] == 1 and (not visited[v]):
                distance[v] = min(distance[v],distance[nextv]
                                              +WMat[nextv,v,1])
    return(distance)

In [ ]:
dijkstra(W,0)

{0: 0, 1: 10.0, 2: 16.0, 3: 81.0, 4: 30.0, 5: 45.0, 6: 35.0}

In [ ]:
def dijkstralist(WList,s):
    infinity = 1 + len(WList.keys())*rows
    max([d for u in WList.keys()
    for (v,d) in WList[u]])
    (visited,distance) = ({},{})
    for v in WList.keys():
        (visited[v],distance[v]) = (False,infinity)

    distance[s] = 0

    for u in WList.keys():
        nextd = min([distance[v] for v in WList.keys()
                        if not visited[v]])
        nextvlist = [v for v in WList.keys()
                        if (not visited[v]) and
                            distance[v] == nextd]
        if nextvlist == []:
            break
        nextv = min(nextvlist)

        visited[nextv] = True
        for (v,d) in WList[nextv]:
            if not visited[v]:
                distance[v] = min(distance[v],distance[nextv]+d)
    return(distance)

In [ ]:
size = 7
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))

In [ ]:
dijkstralist(WL,0)

{0: 0, 1: 10, 2: 16, 3: 81, 4: 30, 5: 45, 6: 35}

In [ ]:
def bellmanford(WMat,s):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows+1
    distance = {}
    for v in range(rows):
        distance[v] = infinity

    distance[s] = 0

    for i in range(rows):
        for u in range(rows):
            for v in range(cols):
                if WMat[u,v,0] == 1:
                    distance[v] = min(distance[v], distance[u]
                                                   + WMat[u,v,1])
    return(distance)

In [ ]:
# Bellman Ford Example
edges = [(0,1,10),(0,7,8),(1,5,2),(2,1,1),(2,3,1),(3,4,3),(4,5,-1),(5,2,-2),(6,1,-4),(6,5,-1),(7,6,1)]

In [ ]:
size = 8
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w
print(W)

[[[ 0.  0.]
  [ 1. 10.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  8.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  2.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  3.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. -1.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 1. -2.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 1. -4.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. -1.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]]]


In [ ]:
bellmanford(W,0)

{0: 0, 1: 5.0, 2: 5.0, 3: 6.0, 4: 9.0, 5: 7.0, 6: 9.0, 7: 8.0}

In [ ]:
def bellmanfordlist(WList,s):
    infinity = 1 + len(WList.keys())*
                    max([d for u in WList.keys()
    distance = {}
    for v in WList.keys():
        distance[v] = infinity

    distance[s] = 0

    for i in WList.keys():
        for u in WList.keys():
            for (v,d) in WList[u]:
                distance[v] = min(distance[v], distance[u] + d)
    return(distance)

In [ ]:
size = 8
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))

In [ ]:
bellmanfordlist(WL,0)

{0: 0, 1: 5, 2: 5, 3: 6, 4: 9, 5: 7, 6: 9, 7: 8}

In [ ]:
def floydwarshall(WMat):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows*rows+1

    SP = np.zeros(shape=(rows,cols,cols+1))
    for i in range(rows):
        for j in range(cols):
            SP[i,j,0] = infinity

    for i in range(rows):
        for j in range(cols):
            if WMat[i,j,0] == 1:
                SP[i,j,0] = WMat[i,j,1]
    print(0)
    print(SP[:,:,0])

    for k in range(1,cols+1):
        for i in range(rows):
            for j in range(cols):
                SP[i,j,k] = min(SP[i,j,k-1],
                                SP[i,k-1,k-1]+SP[k-1,j,k-1])
        print(k)
        print(SP[:,:,k])

    return(SP[:,:,cols])

In [ ]:
floydwarshall(W)

0
[[641.  10. 641. 641. 641. 641. 641.   8.]
 [641. 641. 641. 641. 641.   2. 641. 641.]
 [641.   1. 641.   1. 641. 641. 641. 641.]
 [641. 641. 641. 641.   3. 641. 641. 641.]
 [641. 641. 641. 641. 641.  -1. 641. 641.]
 [641. 641.  -2. 641. 641. 641. 641. 641.]
 [641.  -4. 641. 641. 641.  -1. 641. 641.]
 [641. 641. 641. 641. 641. 641.   1. 641.]]
1
[[641.  10. 641. 641. 641. 641. 641.   8.]
 [641. 641. 641. 641. 641.   2. 641. 641.]
 [641.   1. 641.   1. 641. 641. 641. 641.]
 [641. 641. 641. 641.   3. 641. 641. 641.]
 [641. 641. 641. 641. 641.  -1. 641. 641.]
 [641. 641.  -2. 641. 641. 641. 641. 641.]
 [641.  -4. 641. 641. 641.  -1. 641. 641.]
 [641. 641. 641. 641. 641. 641.   1. 641.]]
2
[[641.  10. 641. 641. 641.  12. 641.   8.]
 [641. 641. 641. 641. 641.   2. 641. 641.]
 [641.   1. 641.   1. 641.   3. 641. 641.]
 [641. 641. 641. 641.   3. 641. 641. 641.]
 [641. 641. 641. 641. 641.  -1. 641. 641.]
 [641. 641.  -2. 641. 641. 641. 641. 641.]
 [637.  -4. 637. 637. 637.  -2. 637. 637.]
 [6

array([[641.,   5.,   5.,   6.,   9.,   7.,   9.,   8.],
       [641.,   1.,   0.,   1.,   4.,   2., 641., 641.],
       [641.,   1.,   1.,   1.,   4.,   3., 641., 641.],
       [641.,   1.,   0.,   1.,   3.,   2., 641., 641.],
       [638.,  -2.,  -3.,  -2.,   1.,  -1., 638., 638.],
       [639.,  -1.,  -2.,  -1.,   2.,   1., 639., 639.],
       [637.,  -4.,  -4.,  -3.,   0.,  -2., 637., 637.],
       [638.,  -3.,  -3.,  -2.,   1.,  -1.,   1., 638.]])

In [ ]:
def primlist(WList):
    infinity = 1 + max([d for u in WList.keys()
                           for (v,d) in WList[u]])
    (visited,distance) = ({},{})
    for v in WList.keys():
        (visited[v],distance[v]) = (False,infinity)

    TreeEdges = []
    visited[0] = True
    for (v,d) in WList[0]:
        distance[v] = d

    for i in WList.keys():
        mindist = infinity
        nextv = None
        for u in WList.keys():
            for (v,d) in WList[u]:
                if visited[u] and (not visited[v]) and d < mindist:
                    mindist = d
                    nextv = v
                    nexte = (u,v)

        if nextv is None:
            break

        visited[nextv] = True
        TreeEdges.append(nexte)
        for (v,d) in WList[nextv]:
            if not visited[v]:
                distance[v] = min(distance[v],d)
    return(TreeEdges)

In [ ]:
# Prims
dedges = [(0,1,10),(0,3,18),(1,2,20),(1,3,6),(2,4,8),(3,4,70)]
edges = dedges + [(j,i,w) for (i,j,w) in dedges]

In [ ]:
size = 5
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))
print(WL)

{0: [(1, 10), (3, 18)], 1: [(2, 20), (3, 6), (0, 10)], 2: [(4, 8), (1, 20)], 3: [(4, 70), (0, 18), (1, 6)], 4: [(2, 8), (3, 70)]}


In [ ]:
primlist(WL)

[(0, 1), (1, 3), (1, 2), (2, 4)]

In [ ]:
def primlist2(WList):
    infinity = 1 + max([d for u in WList.keys()
                           for (v,d) in WList[u]])
    (visited,distance,nbr) = ({},{},{})
    for v in WList.keys():
        (visited[v],distance[v],nbr[v]) = (False,infinity,-1)

    visited[0] = True
    for (v,d) in WList[0]:
        distance[v] = d
        nbr[v] = 0

    for i in range(1,len(WList.keys())):
        nextd = min([distance[v] for v in WList.keys()
                        if not visited[v]])
        nextvlist = [v for v in WList.keys()
                        if (not visited[v]) and
                            distance[v] == nextd]
        if nextvlist == []:
            break
        nextv = min(nextvlist)

        visited[nextv] = True
        for (v,d) in WList[nextv]:
            if not visited[v] and d < distance[v]:
                    (distance[v],nbr) = (d,nextv)
    return(nbr)

In [ ]:
primlist2(WL)

{0: -1, 1: 0, 2: 1, 3: 1, 4: 2}

In [ ]:
def kruskal(WList):
    (edges,component,TE) = ([],{},[])
    for u in WList.keys():
        # Weight as first component to sort easily
        edges.extend([(d,u,v) for (v,d) in WList[u]])
        component[u] = u
    edges.sort()
    print(edges)

    for (d,u,v) in edges:
        if component[u] != component[v]:
            TE.append((u,v))
            c = component[u]
            for w in WList.keys():
                if component[w] == c:
                    component[w] = component[v]
    return(TE)


In [ ]:
# Kruskak example
dedges = [(0,1,10),(0,2,18),(1,2,6),(1,4,20),(2,3,70),(4,5,10),(4,6,10),(5,6,5)]
edges = dedges + [(j,i,w) for (i,j,w) in dedges]

In [ ]:
size = 7
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))

In [ ]:
kruskal(WL)

[(5, 5, 6), (5, 6, 5), (6, 1, 2), (6, 2, 1), (10, 0, 1), (10, 1, 0), (10, 4, 5), (10, 4, 6), (10, 5, 4), (10, 6, 4), (18, 0, 2), (18, 2, 0), (20, 1, 4), (20, 4, 1), (70, 2, 3), (70, 3, 2)]


[(5, 6), (1, 2), (0, 1), (4, 5), (1, 4), (2, 3)]